# Generated by Django 5.1 on 2025-01-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('esp_32', models.CharField(blank=True, max_length=255, null=True)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=9, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=9, max_digits=9, null=True)),
                ('esp_8266_num1', models.CharField(default='', max_length=255)),
                ('esp_8266_num2', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
