# Generated by Django 5.1 on 2025-01-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='gps_latitude',
            field=models.DecimalField(blank=True, decimal_places=255, max_digits=255, null=True),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='gps_longitude',
            field=models.DecimalField(blank=True, decimal_places=255, max_digits=255, null=True),
        ),
    ]
