# Generated by Django 5.1 on 2025-01-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_alter_devicedata_gps_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='esp_32',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='gps_latitude',
            field=models.DecimalField(decimal_places=255, max_digits=255, null=True),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='gps_longitude',
            field=models.DecimalField(decimal_places=255, max_digits=255, null=True),
        ),
    ]
