# Generated by Django 5.1 on 2025-01-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_alter_devicedata_esp_32_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='gps_latitude',
            field=models.DecimalField(decimal_places=7, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='gps_longitude',
            field=models.DecimalField(decimal_places=7, max_digits=11, null=True),
        ),
    ]
