# Generated by Django 5.1 on 2024-12-20 13:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_delete_mymodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
